// web/src/pages/LandingPage.tsx
const LandingPage = () => {
  return (
    <div className="mx-60">
      <header className="h-screen flex justify-center items-center">
        <h1 className="font-bold text-6xl text-center">Catch the moments that matter — rewind, reflect, relive.</h1>
      </header>
      <section>
        <p className="font-medium text-lg">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vero dolores nam molestiae dicta exercitationem explicabo culpa velit qui natus sed non nihil earum quod, cumque obcaecati ex aspernatur doloribus quam.</p>
      </section>
    </div>
  )
}

export default LandingPage

// web/src/views/LandingPage.vue
<script setup lang="ts">
  
</script>

<template>
  <div class="mx-60">
    <header class="h-screen flex justify-center items-center">
      <h1 class="font-bold text-6xl text-center">Catch the moments that matter — rewind, reflect, relive.</h1>
    </header>
    <section>
      <p class="font-medium text-lg">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vero dolores nam molestiae dicta exercitationem explicabo culpa velit qui natus sed non nihil earum quod, cumque obcaecati ex aspernatur doloribus quam.</p>
    </section>
  </div>
</template>
